version: 1.0.{build}

install: 
  - cinst autohotkey.install

build: off

before_test:
  - cmd: cd test

#test_script: 
#  - test.cmd

# you can call ahk script it seems
test_script: 
  - v.cmd

after_test:
  - cmd: type testoutput.txt
