version: 1.0.{build}

install: 
  - cinst autohotkey.install

build: off

environment:
  access_token:
    secure: oZCQbV/KnkREW7Lr8SSrkvtHC4V7xsIVAHb1EXkv8BeKABdPPxjgmcwlHuJVUBOv

before_test:
  - cmd: cd test

test_script: 
  - update.ahk
#  - vscript.cmd test.ahk

on_success:
  - cd ..
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "hi5ghub@gmail.com"
  - git config --global user.name "hi5"
  - git checkout master
  - git status
  - git add av.md
  - git commit -a -m "updating [skip appveyor]"
  - git remote -v
  - git push -v origin master
